version: '3'

services:
  nginx:
    image: nginx:1.13
    container_name: nginx
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./dist:/usr/share/nginx/html