name: Node.js CI
on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code
      
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: v18.9.1
        cache: 'npm'
    - run: npm install
    - run: npm run build

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: carlosgarciasmallworldfs/github-actions-tutorial
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
